[package]
name = "fuselog_apply"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = "2.0.1"
env_logger = "0.11.8"
fuselog_core = { path = "../fuselog_core" }
log = "0.4.27"
uds = "0.4.2"
zstd = "0.13.3"
