[package]
name = "fuselog_core"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = "2.0.1"
env_logger = "0.11.8"
fuser = "0.15.1"
libc = "0.2.172"
log = "0.4.27"
serde = {version = "1.0.219", features = ["derive"]}
